# Generated by Django 3.2.12 on 2022-02-28 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220228_1118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='cretaed_date',
            new_name='created_date',
        ),
    ]
