# Generated by Django 3.2.12 on 2022-04-22 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comingsoon', '0002_alter_notify_me_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notify_me',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='notify_me',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
